"""Add paper analyses table

Revision ID: 20a086cb0da3
Revises: 
Create Date: 2026-03-23 11:33:47.804694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20a086cb0da3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('publication_readiness', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cover_letters', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cover_letters', 'paper_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cover_letters', 'journal_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('cover_letters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('cover_letters_paper_id_fkey'), 'cover_letters', type_='foreignkey')
    op.drop_constraint(op.f('cover_letters_user_id_fkey'), 'cover_letters', type_='foreignkey')
    op.create_foreign_key(None, 'cover_letters', 'papers', ['paper_id'], ['id'])
    op.create_foreign_key(None, 'cover_letters', 'users', ['user_id'], ['id'])
    op.alter_column('generated_templates', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('generated_templates', 'journal_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('generated_templates', 'format_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('generated_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('generated_templates_paper_id_fkey'), 'generated_templates', type_='foreignkey')
    op.drop_constraint(op.f('generated_templates_user_id_fkey'), 'generated_templates', type_='foreignkey')
    op.create_foreign_key(None, 'generated_templates', 'papers', ['paper_id'], ['id'])
    op.create_foreign_key(None, 'generated_templates', 'users', ['user_id'], ['id'])
    op.alter_column('journals', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journals', 'publisher',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journals', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journals', 'quartile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journals', 'speed',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journals', 'cost_note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journals', 'submission_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journals', 'impact_factor',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_journals_name'), table_name='journals')
    op.alter_column('papers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('papers', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('papers', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('papers', 'file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('papers', 'file_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('papers', 'plagiarism_score',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('papers', 'abstract_quality_score',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('papers', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_papers_created_at'), table_name='papers')
    op.drop_index(op.f('idx_papers_user_id'), table_name='papers')
    op.drop_constraint(op.f('papers_user_id_fkey'), 'papers', type_='foreignkey')
    op.create_foreign_key(None, 'papers', 'users', ['user_id'], ['id'])
    op.alter_column('saved_journals', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('saved_journals', 'journal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('saved_journals', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_saved_journals_user'), table_name='saved_journals')
    op.drop_constraint(op.f('saved_journals_user_id_journal_id_key'), 'saved_journals', type_='unique')
    op.drop_constraint(op.f('saved_journals_user_id_fkey'), 'saved_journals', type_='foreignkey')
    op.drop_constraint(op.f('saved_journals_journal_id_fkey'), 'saved_journals', type_='foreignkey')
    op.create_foreign_key(None, 'saved_journals', 'journals', ['journal_id'], ['id'])
    op.create_foreign_key(None, 'saved_journals', 'users', ['user_id'], ['id'])
    op.alter_column('submissions', 'paper_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('submissions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('submissions', 'journal_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('submissions', 'journal_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('submissions', 'current_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('submissions', 'reminder_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_submissions_paper_id'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_submitted_at'), table_name='submissions')
    op.drop_index(op.f('idx_submissions_user_id'), table_name='submissions')
    op.drop_constraint(op.f('submissions_user_id_fkey'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_paper_id_fkey'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'papers', ['paper_id'], ['id'])
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'university',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_firebase_uid_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_firebase_uid_key'), 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'university',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_paper_id_fkey'), 'submissions', 'papers', ['paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('submissions_user_id_fkey'), 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_index(op.f('idx_submissions_submitted_at'), 'submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('idx_submissions_paper_id'), 'submissions', ['paper_id'], unique=False)
    op.alter_column('submissions', 'reminder_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('submissions', 'current_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('submissions', 'journal_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('submissions', 'journal_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('submissions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('submissions', 'paper_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'saved_journals', type_='foreignkey')
    op.drop_constraint(None, 'saved_journals', type_='foreignkey')
    op.create_foreign_key(op.f('saved_journals_journal_id_fkey'), 'saved_journals', 'journals', ['journal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('saved_journals_user_id_fkey'), 'saved_journals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('saved_journals_user_id_journal_id_key'), 'saved_journals', ['user_id', 'journal_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_saved_journals_user'), 'saved_journals', ['user_id'], unique=False)
    op.alter_column('saved_journals', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_journals', 'journal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('saved_journals', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.create_foreign_key(op.f('papers_user_id_fkey'), 'papers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_papers_user_id'), 'papers', ['user_id'], unique=False)
    op.create_index(op.f('idx_papers_created_at'), 'papers', ['created_at'], unique=False)
    op.alter_column('papers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('papers', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('papers', 'abstract_quality_score',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('papers', 'plagiarism_score',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('papers', 'file_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('papers', 'file_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('papers', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('papers', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('papers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_journals_name'), 'journals', ['name'], unique=False)
    op.alter_column('journals', 'impact_factor',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('journals', 'submission_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journals', 'cost_note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journals', 'speed',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journals', 'quartile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journals', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journals', 'publisher',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('journals', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'generated_templates', type_='foreignkey')
    op.drop_constraint(None, 'generated_templates', type_='foreignkey')
    op.create_foreign_key(op.f('generated_templates_user_id_fkey'), 'generated_templates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('generated_templates_paper_id_fkey'), 'generated_templates', 'papers', ['paper_id'], ['id'], ondelete='SET NULL')
    op.alter_column('generated_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_templates', 'format_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_templates', 'journal_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('generated_templates', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.drop_constraint(None, 'cover_letters', type_='foreignkey')
    op.create_foreign_key(op.f('cover_letters_user_id_fkey'), 'cover_letters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cover_letters_paper_id_fkey'), 'cover_letters', 'papers', ['paper_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cover_letters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_letters', 'journal_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('cover_letters', 'paper_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cover_letters', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('paper_analyses')
    # ### end Alembic commands ###
